// Builds js/icons.js from the SVG files in src/svg.
//
// Usage (from the project root):   node tools/build-icons.js
//
// Why a build step: the page can't read files from src/svg at run time when it is opened straight from
// disk (browsers block that), and an <img> can't take the theme colour. So each SVG is inlined into
// js/icons.js with every hard-coded colour turned into `currentColor`, which lets an icon follow the
// text colour of the button it sits in (theme, light/dark, hover, danger...).
//
// To add an icon: drop the .svg in src/svg and run this again. The icon's name is the file name
// without extension (e.g. dark_mode.svg -> 'dark_mode').

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const srcDir = path.join(root, 'src', 'svg');
const outFile = path.join(root, 'js', 'icons.js');

const isPaint = (value) => !/^(none|currentcolor|transparent|inherit)$/i.test(value.trim());

function convert(name, source) {
  const match = /<svg\b([^>]*)>([\s\S]*?)<\/svg>/i.exec(source);
  if (!match) throw new Error(name + ': no <svg> element found');
  const attrs = match[1];
  const viewBox = (/viewBox="([^"]+)"/.exec(attrs) || [])[1];
  if (!viewBox) throw new Error(name + ': the <svg> has no viewBox');

  let body = match[2]
    .replace(/<!--[\s\S]*?-->/g, '')                       // comments
    .replace(/<title\s*\/>|<title>[\s\S]*?<\/title>/gi, '') // titles (an icon is decoration, not content)
    .replace(/<desc>[\s\S]*?<\/desc>|<defs>\s*<\/defs>/gi, '')  // editor leftovers
    .replace(/\s+(?:sketch:type|data-name)="[^"]*"/g, '')
    .replace(/\s+id="[^"]*"/g, '')                          // ids would clash when several icons are inlined
    .replace(/\b(fill|stroke)="([^"]*)"/g, (all, attr, value) => (isPaint(value) ? attr + '="currentColor"' : all))
    .replace(/\s+/g, ' ')
    .replace(/> </g, '><')
    .trim();

  // The root <svg> decides how shapes without their own fill are painted, and the inlined icon no longer
  // has that root: fill="none" (outline icons: only the stroke is drawn) must survive, and a colour
  // (or no fill at all, which the browser paints black) must become currentColor. Shapes that set
  // their own fill keep it.
  const rootFill = /\bfill="([^"]*)"/.exec(attrs);
  if (rootFill && !isPaint(rootFill[1])) body = '<g fill="' + rootFill[1] + '">' + body + '</g>';
  else body = '<g fill="currentColor">' + body + '</g>';

  return { viewBox, body };
}

const icons = {};
fs.readdirSync(srcDir)
  .filter((file) => file.toLowerCase().endsWith('.svg'))
  .sort()
  .forEach((file) => {
    const name = path.basename(file, path.extname(file));
    icons[name] = convert(name, fs.readFileSync(path.join(srcDir, file), 'utf8'));
  });

const lines = Object.keys(icons).map((name) => '    ' + JSON.stringify(name) + ': ' + JSON.stringify(icons[name]));

const output = `// GENERATED by tools/build-icons.js from src/svg/*.svg. Do not edit by hand: change the SVGs and
// run \`node tools/build-icons.js\` again.
(function (C) {
  'use strict';

  var SVG_NS = 'http://www.w3.org/2000/svg';

  var ICONS = {
${lines.join(',\n')}
  };

  // A new inline <svg class="icon"> for the icon called \`name\`. It has no colour of its own: it takes
  // the text colour of whatever contains it. An unknown name gives an empty icon instead of an error.
  function create(name) {
    var def = ICONS[name];
    var svg = document.createElementNS(SVG_NS, 'svg');
    svg.setAttribute('class', 'icon');
    svg.setAttribute('aria-hidden', 'true');
    svg.setAttribute('focusable', 'false');
    if (def) {
      svg.setAttribute('viewBox', def.viewBox);
      svg.innerHTML = def.body;      // static markup produced by the build script, never user input
    }
    return svg;
  }

  // Fills every <span data-icon="name"> under \`scope\` with its icon (used by the static HTML).
  function mount(scope) {
    var slots = (scope || document).querySelectorAll('[data-icon]');
    for (var i = 0; i < slots.length; i++) slots[i].replaceChildren(create(slots[i].getAttribute('data-icon')));
  }

  C.icons = { create: create, mount: mount };
})(window.Cancionero = window.Cancionero || {});
`;

fs.writeFileSync(outFile, output, 'utf8');
console.log('js/icons.js: ' + Object.keys(icons).length + ' icons (' + Object.keys(icons).join(', ') + ')');
