// Builds js/ocarina-image.js: the ocarina picture of the fingering diagrams as a data address.
//
// Usage (from the project root):   node tools/build-images.js
//
// Why a build step: the score image (js/score-image.js) draws the diagrams on a canvas. A canvas that has
// drawn a file loaded from disk can no longer be saved as an image when the page itself is opened from disk
// (file://), because the browser treats every file as a different origin. A picture written into a script
// as a data address is always allowed. Run this again after changing src/img/ocarina_base.png.

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const source = path.join(root, 'src', 'img', 'ocarina_base.png');
const outFile = path.join(root, 'js', 'ocarina-image.js');

const data = fs.readFileSync(source).toString('base64');

fs.writeFileSync(outFile, [
  '// Generated by tools/build-images.js from src/img/ocarina_base.png. Do not edit by hand.',
  '(function (C) {',
  "  'use strict';",
  "  C.ocarinaImage = 'data:image/png;base64," + data + "';",
  "})(window.Songbook = window.Songbook || {});",
  ''
].join('\n'));

console.log('js/ocarina-image.js: ' + Math.round(data.length / 1024) + ' KB');
